// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250328055947_Ini")]
    partial class Ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.ToTable("stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Technology company that designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories.",
                            Name = "Apple Inc.",
                            Price = 187.41m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Technology company that develops, licenses, and supports software, services, devices, and solutions.",
                            Name = "Microsoft Corporation",
                            Price = 403.78m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Online retailer and web service provider.",
                            Name = "Amazon.com, Inc.",
                            Price = 178.75m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Technology company that specializes in Internet-related services and products.",
                            Name = "Alphabet Inc.",
                            Price = 153.51m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Technology company that focuses on social media and technology.",
                            Name = "Meta Platforms, Inc.",
                            Price = 485.58m,
                            Symbol = "META"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Electric vehicle and clean energy company.",
                            Name = "Tesla, Inc.",
                            Price = 175.34m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Technology company that designs graphics processing units.",
                            Name = "NVIDIA Corporation",
                            Price = 952.76m,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Financial services company.",
                            Name = "JPMorgan Chase & Co.",
                            Price = 198.47m,
                            Symbol = "JPM"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Digital payments company.",
                            Name = "Visa Inc.",
                            Price = 267.32m,
                            Symbol = "V"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Pharmaceutical and medical devices company.",
                            Name = "Johnson & Johnson",
                            Price = 153.92m,
                            Symbol = "JNJ"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Retail corporation that operates a chain of hypermarkets.",
                            Name = "Walmart Inc.",
                            Price = 65.32m,
                            Symbol = "WMT"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Consumer goods corporation.",
                            Name = "Procter & Gamble Co.",
                            Price = 161.43m,
                            Symbol = "PG"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Multinational investment bank and financial services company.",
                            Name = "Bank of America Corp.",
                            Price = 39.25m,
                            Symbol = "BAC"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Health insurance company.",
                            Name = "UnitedHealth Group Inc.",
                            Price = 528.72m,
                            Symbol = "UNH"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Home improvement retailer.",
                            Name = "Home Depot Inc.",
                            Price = 343.17m,
                            Symbol = "HD"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Multinational oil and gas corporation.",
                            Name = "Exxon Mobil Corp.",
                            Price = 115.44m,
                            Symbol = "XOM"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Pharmaceutical corporation.",
                            Name = "Pfizer Inc.",
                            Price = 27.56m,
                            Symbol = "PFE"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Designer, developer, and global supplier of semiconductor devices.",
                            Name = "Broadcom Inc.",
                            Price = 1256.83m,
                            Symbol = "AVGO"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Technology company that develops networking hardware and software.",
                            Name = "Cisco Systems, Inc.",
                            Price = 48.90m,
                            Symbol = "CSCO"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Telecommunications conglomerate.",
                            Name = "Verizon Communications Inc.",
                            Price = 41.75m,
                            Symbol = "VZ"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Chain of membership-only warehouse clubs.",
                            Name = "Costco Wholesale Corp.",
                            Price = 721.24m,
                            Symbol = "COST"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Multinational energy corporation.",
                            Name = "Chevron Corp.",
                            Price = 146.27m,
                            Symbol = "CVX"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Multinational computer software company.",
                            Name = "Adobe Inc.",
                            Price = 525.31m,
                            Symbol = "ADBE"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Telecommunications conglomerate.",
                            Name = "Comcast Corp.",
                            Price = 42.15m,
                            Symbol = "CMCSA"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Athletic footwear and apparel corporation.",
                            Name = "Nike, Inc.",
                            Price = 81.24m,
                            Symbol = "NKE"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Streaming service and production company.",
                            Name = "Netflix, Inc.",
                            Price = 678.69m,
                            Symbol = "NFLX"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Food, snack, and beverage corporation.",
                            Name = "PepsiCo, Inc.",
                            Price = 174.81m,
                            Symbol = "PEP"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Beverage corporation.",
                            Name = "Coca-Cola Co.",
                            Price = 60.37m,
                            Symbol = "KO"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Medical devices and health care company.",
                            Name = "Abbott Laboratories",
                            Price = 108.25m,
                            Symbol = "ABT"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Pharmaceutical company.",
                            Name = "Merck & Co., Inc.",
                            Price = 121.45m,
                            Symbol = "MRK"
                        });
                });

            modelBuilder.Entity("backend.Models.TradeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("entryprice");

                    b.Property<bool>("IsHolding")
                        .HasColumnType("boolean")
                        .HasColumnName("isholding");

                    b.Property<decimal>("PNL")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pnl");

                    b.Property<int>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stockid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.ToTable("tradehistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryPrice = 150.25m,
                            IsHolding = true,
                            PNL = 37.16m,
                            StockId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryPrice = 380.50m,
                            IsHolding = true,
                            PNL = 23.28m,
                            StockId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryPrice = 185.30m,
                            IsHolding = false,
                            PNL = -6.55m,
                            StockId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            Username = "demo"
                        });
                });

            modelBuilder.Entity("backend.Models.TradeHistory", b =>
                {
                    b.HasOne("backend.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
